apiVersion: v1
kind: Secret
metadata:
  name: relay-smtp
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  tx-smtp-relay-password: {{ .Values.smtp.relayPassword | b64enc }}
